### ISSUE TITLE
TPCANTimestamp corrupted starting in version 0.9.0

### ISSUE THREAD

**Issue by babldev** [mac-can/PCBUSB-Library#2]
After upgrading from the 0.8.1 working driver to 0.9.0+, message timestamps are corrupted when accessed using https://github.com/hardbyte/python-can

0.8.1 (working)
<img width="376" alt="Screen Shot 2021-02-09 at 2 47 54 PM" src="https://user-images.githubusercontent.com/220799/107439059-566df080-6ae6-11eb-9b11-42aac4b037f4.png">

0.9.0 (broken)
<img width="451" alt="Screen Shot 2021-02-09 at 2 49 25 PM" src="https://user-images.githubusercontent.com/220799/107439075-5c63d180-6ae6-11eb-8b0b-88ceb239ea2f.png">

Did the serialization of timestamp offsets change in this release?
https://github.com/hardbyte/python-can/blob/291af86e3898229a8bacebd82f4ff7a8b81a41c0/can/interfaces/pcan/basic.py#L505-L518

My setup:
MacBook Pro (15-inch, 2018)
macOS Catalina 10.15.4 (19E266)

**Comment by babldev** [comment]
Related https://github.com/hardbyte/python-can/pull/947

**Comment by mac-can** [comment]
That´s true. With version 0.9 the replacement for Windows data type `DWORD` (which is frequently used by PEAK´s PCANBasic API) was changed from `unsigned long` to `UInt32`. On Windows the data type `long` is 32-bit wide, and on Unix based system it is 64-bit wide. With this change the data types matches on all OS.

This issue is also tracked in the [python-can](https://github.com/hardbyte/python-can/issues/957) project. Meanwhile PEAK added the PCBUSB library to their Python wrapper. My suggestion is to take this one instead of the patched one from the python-can repo. And of course the latest [PCBUSB](https://mac-can.com/) release.

**Comment by babldev** [comment]
thanks for the clarification, I can work with @kail on the python-can patch
