### ISSUE TITLE
Apple Silicon (ARM M1) not supported

### ISSUE THREAD

**Issue by csrubin** [mac-can/PCBUSB-Library#3]
Currently this driver only seems to support x86 architectures. Is there any way to port this over to M1 chips, or is there another workaround to use to solve compatibility problems?

**Comment by mac-can** [comment]
You are right, currently only the x86_64 architecture is supported by the PCBUSB library. There is theoretically a good chance that it would compile and run on the Apple Silicon (ARM M1); see [RusokuCAN issue #6](https://github.com/mac-can/RusokuCAN/issues/6).

Unfortunately, I don't have a Mac with an M1 chip. And - sorry for that - even if a cross-compilation would succeed, I would not release untested software. And it is and remains closed-source.

Cheers

_When I started the project eight years ago, I was asked if the PowerPC architecture was supported. Isn´t it funny_ 😎

**Comment by gregington** [comment]
Is there any progress on an Apple Silicon build? Next week sees an expected release of MacBook Pro models with M1X chipsets; it won't be long until intel Macs won't be available for purchase.

**Comment by gregington** [comment]
Thanks @csrubin, I got it working using the `arch -x86_64` command.

Using the prefix `arch-x86_64` will load the subsequent universal binary as x86 (instead of Apple Silicon) and will allow Rosetta to work for dynamically linked libraries. Otherwise the binary will be run as Apple Silicon and Rosetta won't be used. For example, you can run `arch -x86_64 python` which will run the x86 python binary.

See also https://apple.stackexchange.com/questions/409746/run-everything-in-rosetta-2-on-silicon-mac and https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment.

**Comment by mac-can** [comment]
The [PCBUSB dylib ](https://www.uv-software.de/files/downloads/MacCAN/PCANUSB/Library/OS_X_Library_for_PCANUSB_v0.10.ub.tar.gz) compiled as Universal macOS Binary can be downloded here:
https://www.uv-software.de/dokuwiki/doku.php?id=uvs:programs:pcbusb_library
It should run on both architectures, but it is not tested on arm64.

Happy CANgineering.

**Comment by mac-can** [comment]
I am happy to announce version 0.10.1 (Service Release). It is now officially available as Universal macOS Binary.
